DROP TABLE IF EXISTS member;

CREATE TABLE member (
  id INT PRIMARY KEYNOT NULL GENERATED ALWAYS AS IDENTITY,
  f_name TEXT NOT NULL,
  l_name TEXT NOT NULL,
  dob DATE NOT NULL,
  ssn TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  create_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW()
);